void _puts_recursion(char *s);
int _putchar(char c);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int natural_sqrt_recursion(int n, int i);
int is_prime_number(int n);
int _is_prime(int n, int i);
int is_palindrome(char *s);
int check_if_palindrome(char *s, int i, int len);
int find_strlen(char *s);
int wildcmp(char *s1, char *s2);
